version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.18"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.17"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.16"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.15"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  
