---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ssp-kubevirt-io-v1beta2-ssp
  failurePolicy: Fail
  name: validation.v1beta2.ssp.kubevirt.io
  rules:
  - apiGroups:
    - ssp.kubevirt.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - ssps
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ssp-kubevirt-io-v1beta3-ssp
  failurePolicy: Fail
  name: validation.v1beta3.ssp.kubevirt.io
  rules:
  - apiGroups:
    - ssp.kubevirt.io
    apiVersions:
    - v1beta3
    operations:
    - CREATE
    - UPDATE
    resources:
    - ssps
  sideEffects: None
