# permissions for end users to view ssps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssp-viewer-role
rules:
- apiGroups:
  - ssp.kubevirt.io
  resources:
  - ssps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ssp.kubevirt.io
  resources:
  - ssps/status
  verbs:
  - get
