apiVersion: ssp.kubevirt.io/v1beta2
kind: SSP
metadata:
  name: ssp-sample
  namespace: kubevirt
spec:
  commonTemplates:
    namespace: kubevirt
  templateValidator:
    replicas: 2
  featureGates:
    deployVmConsoleProxy: true
